### get all users
GET http://localhost:3000/api/priceSubscriptions


### get user by id
GET http://localhost:3000/api/priceSubscriptions/1

### create new user
POST http://localhost:3000/api/priceSubscriptions
Content-Type: application/json 

{
  "id": "1",
  "dateStart": "2024-06-17",
  "price": "150",
}
  
### Edit/modify user (PUT - recurso completo/objeto con estado final)
PUT http://localhost:3000/api/priceSubscriptions/1
Content-Type: application/json

{
  "id": "1",
  "dateStart": "2024-06-17",
  "price": "100",
}

### Edit/modify user (PATCH - Modificaciones parciales/modificaciones incrementales)
PATCH http://localhost:3000/api/priceSubscriptions/1
Content-Type: application/json

{
  "dateStart": "2024-05-17"

}

### delete user
DELETE http://localhost:3000/api/priceSubscriptions/1